// @vitest-environment jsdom
import { fireEvent, render, screen, cleanup } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { useState } from 'react';
import { getMission } from '../../data/missions';
import { initialProgress, type Progress } from '../../game/progress';
import { MemoryMission } from './MemoryMission';
afterEach(cleanup);
const mission=getMission('memory')!;
function Harness({level='scientist',initial}:{level?:'explorer'|'scientist'|'expert';initial?:Progress}){const [progress,setProgress]=useState<Progress>(initial??{...initialProgress(),level});return <><MemoryMission mission={mission} progress={progress} onProgress={setProgress} onBack={()=>undefined}/><output data-testid="saved">{JSON.stringify(progress)}</output></>}
describe('mission Mémoire',()=>{
  it('classe en RAM et en stockage par sélection puis dépôt',async()=>{const user=userEvent.setup();render(<Harness/>);await user.click(screen.getByRole('button',{name:/Calcul en cours/i}));await user.click(screen.getByRole('button',{name:/Table de travail/i}));await user.click(screen.getByRole('button',{name:/Photographie enregistrée/i}));await user.click(screen.getByRole('button',{name:/Bibliothèque/i}));expect(screen.getByLabelText(/2\/8 cartes classées/i)).toBeTruthy();});
  it('refuse un mauvais classement',async()=>{const user=userEvent.setup();render(<Harness/>);await user.click(screen.getByRole('button',{name:/Calcul en cours/i}));await user.click(screen.getByRole('button',{name:/Bibliothèque/i}));expect(screen.getByText(/Ne confonds pas/i)).toBeTruthy();});
  it('accepte un glissement tactile',()=>{render(<Harness/>);const item=screen.getByRole('button',{name:/Photographie enregistrée/i});const target=screen.getByRole('button',{name:/Bibliothèque/i});Object.defineProperty(document,'elementFromPoint',{configurable:true,value:vi.fn(()=>target)});fireEvent.pointerDown(item,{pointerId:2,pointerType:'touch',clientX:1,clientY:1});fireEvent.pointerMove(item,{pointerId:2,pointerType:'touch',clientX:80,clientY:60});fireEvent.pointerUp(item,{pointerId:2,pointerType:'touch',clientX:80,clientY:60});expect(screen.getByLabelText(/1\/8 cartes classées/i)).toBeTruthy();});
  it('présente les deux cas ambigus au niveau Expert',()=>{render(<Harness level="expert"/>);expect(screen.getByRole('button',{name:/Image modifiée non enregistrée/i})).toBeTruthy();expect(screen.getByRole('button',{name:/Application installée/i})).toBeTruthy();expect(screen.getByRole('button',{name:/Application en cours/i})).toBeTruthy();});
  it('réussit, enregistre 2 et restaure une progression',async()=>{const user=userEvent.setup();render(<Harness/>);for(const title of ['Calcul en cours','Onglet actuellement ouvert','Position actuelle de l’automate','Image modifiée non enregistrée']){await user.click(screen.getByRole('button',{name:new RegExp(title,'i')}));await user.click(screen.getByRole('button',{name:/Table de travail/i}));}for(const title of ['Photographie enregistrée','Carnet scientifique sauvegardé','Carte téléchargée','Archive d’observations']){await user.click(screen.getByRole('button',{name:new RegExp(title,'i')}));await user.click(screen.getByRole('button',{name:/Bibliothèque/i}));}expect(screen.getByLabelText(/Fragment découvert : 2/i)).toBeTruthy();expect(screen.getByTestId('saved').textContent).toContain('"memory":"2"');expect(screen.queryByRole('textbox')).toBeNull();cleanup();render(<Harness initial={{...initialProgress(),level:'scientist',digitalPlacements:{memory:{calculation:'ram'}}}}/>);expect(screen.getByLabelText(/1\/8 cartes classées/i)).toBeTruthy();});
  it('remet localement un classement partiel à zéro',async()=>{const user=userEvent.setup();render(<Harness/>);await user.click(screen.getByRole('button',{name:/Calcul en cours/i}));await user.click(screen.getByRole('button',{name:/Table de travail/i}));await user.click(screen.getByRole('button',{name:/Réinitialiser le classement/i}));expect(screen.getByLabelText(/0\/8 cartes classées/i)).toBeTruthy();expect(screen.getByTestId('saved').textContent).toContain('"memory":{}');});
});
