import { useMemo, useState, type Dispatch, type SetStateAction } from 'react';
import type { Level, Mission } from '../../data/missions';
import { ambiguousObservation, balancedTraining, biasedTraining, classifyDetailed, clearObservation, newObservations, type ClassificationResult, type Observation } from '../../game/classifier';
import { DraggableItem } from '../../game/interactions/DraggableItem';
import { DropZone } from '../../game/interactions/DropZone';
import { usePlacementGame } from '../../game/interactions/usePlacementGame';
import { initialAIMission, validateFragment, type Progress } from '../../game/progress';

type Props = { mission: Mission; progress: Progress; onProgress: Dispatch<SetStateAction<Progress>>; onBack: () => void };
const rules = Object.fromEntries(newObservations.map((item) => [item.id, classifyDetailed(item, balancedTraining).predictedClass]));
const without = (record: Record<string, number>, key: string) => { const next = { ...record }; delete next[key]; return next; };
const copy: Record<Level, { intro: string; classify: string; experiment: string; conclusion: string }> = {
  explorer: { intro: 'Regarde les quatre exemples et leurs familles. La machine compare avec ce qu’on lui a montré.', classify: 'Touche une observation, puis sa famille. Regarde les étoiles et les formes proches.', experiment: 'Observe comment les exemples peuvent faire changer la réponse.', conclusion: 'La machine compare avec les exemples qu’on lui a montrés.' },
  scientist: { intro: 'Ces données d’apprentissage ont deux caractéristiques : luminosité et régularité.', classify: 'Classe les observations selon les trois exemples les plus proches.', experiment: 'Le vote des trois voisins produit une classification, pas une certitude.', conclusion: 'Une IA est un programme qui classe à partir d’exemples. Ses données influencent sa réponse.' },
  expert: { intro: 'Chaque observation est un vecteur (luminosité, régularité). Le classifieur simple utilisera k = 3.', classify: 'Compare les distances entre vecteurs. À distance égale, l’identifiant fixe l’ordre des voisins.', experiment: 'La classe majoritaire des k = 3 voisins donne une prédiction, distincte de la vérité. En égalité de votes, la règle choisit parasite.', conclusion: 'Ce k-NN simple ne représente pas toutes les IA : prédiction, confiance et vérité restent distinctes.' },
};

function SkyPlot({ training, selected, result, onExample }: { training: readonly Observation[]; selected?: Observation; result?: ClassificationResult; onExample?: (id: string) => void }) {
  const neighborIds = new Set(result?.neighbors.map(({ observation }) => observation.id));
  return <div className="ai-plot-wrap"><div className="ai-plot" role="group" aria-label="Graphique : luminosité de 0 à 10 horizontalement, régularité de 0 à 10 verticalement">
    <span className="ai-axis ai-axis--x">Luminosité →</span><span className="ai-axis ai-axis--y">Régularité ↑</span>
    {selected && result?.neighbors.map(({ observation }) => { const dx = (observation.brightness - selected.brightness) * 10; const dy = (selected.regularity - observation.regularity) * 10; return <i key={`line-${observation.id}`} className="ai-distance-line" style={{ left: `${selected.brightness * 10}%`, bottom: `${selected.regularity * 10}%`, width: `${Math.hypot(dx, dy)}%`, transform: `rotate(${Math.atan2(dy, dx)}rad)` }} aria-hidden="true" />; })}
    {training.map((item) => <button key={item.id} type="button" className={`ai-point ai-point--${item.label} ${neighborIds.has(item.id) ? 'is-neighbor' : ''}`} style={{ left: `${item.brightness * 10}%`, bottom: `${item.regularity * 10}%` }} onClick={() => onExample?.(item.id)} aria-label={`${item.name}, ${item.label}, luminosité ${item.brightness}, régularité ${item.regularity}`}><span aria-hidden="true">{item.label === 'signal' ? '★' : '◆'}</span><small>{item.name}</small></button>)}
    {selected && <span className="ai-point ai-point--unknown" style={{ left: `${selected.brightness * 10}%`, bottom: `${selected.regularity * 10}%` }} aria-label={`${selected.name}, luminosité ${selected.brightness}, régularité ${selected.regularity}`}><span aria-hidden="true">◎</span><small>{selected.name}</small></span>}
  </div><p className="ai-plot-description">Horizontal : luminosité ; vertical : régularité, de 0 à 10. ★ signal, ◆ parasite, ◎ observation inconnue. Les contours lumineux montrent les voisins retenus.</p></div>;
}

function NeighborVote({ result, level }: { result: ClassificationResult; level: Level }) {
  return <div className="ai-vote"><h3>Les trois voisins qui votent</h3><ul>{result.neighbors.map(({ observation, distance }) => <li key={observation.id}><span aria-hidden="true">{observation.label === 'signal' ? '★' : '◆'}</span><b>{observation.name}</b><span>{observation.label}</span>{level === 'expert' && <small>distance {distance.toFixed(2)}</small>}</li>)}</ul><p><b>{result.votes.signal} signal{result.votes.signal > 1 ? 's' : ''} · {result.votes.parasite} parasite{result.votes.parasite > 1 ? 's' : ''}</b> → Décision : <strong>{result.predictedClass.toUpperCase()}</strong></p><small>Indice de vote : {Math.max(result.votes.signal, result.votes.parasite)}/3 voisins, ce n’est pas une probabilité ni une preuve.</small></div>;
}

export function AIMission({ mission, progress, onProgress, onBack }: Props) {
  const level = progress.level ?? 'scientist';
  const state = progress.aiMission;
  const complete = progress.completed.includes('ai');
  const [selectedExample, setSelectedExample] = useState<string | null>(null);
  const [selectedObservation, setSelectedObservation] = useState<string | null>(null);
  const [message, setMessage] = useState('Choisis un point ou une carte pour voir ses caractéristiques.');
  const game = usePlacementGame({ rules, initialPlacements: state.placements,
    errorMessage: (id) => { const item = newObservations.find((entry) => entry.id === id)!; const expected = rules[id]; return `${item.name} ressemble davantage aux ${expected === 'signal' ? 'signaux' : 'parasites'} déjà rencontrés. Compare luminosité et régularité.`; },
    successMessage: (id) => `${id.toUpperCase()} est classée. Les voisins les plus proches ont guidé la décision.`,
    onPlacementChange: (placements) => onProgress((current) => ({ ...current, aiMission: { ...current.aiMission, placements: placements as Progress['aiMission']['placements'] } })),
    onWrongPlacement: () => onProgress((current) => validateFragment(current, 'ai', '').progress),
    onComplete: () => onProgress((current) => ({ ...current, aiMission: { ...current.aiMission, phase: 3 } })),
  });
  const phase = complete ? 4 : state.phase;
  const chosen = balancedTraining.find((item) => item.id === selectedExample);
  const active = newObservations.find((item) => item.id === selectedObservation) ?? newObservations.find((item) => item.id === game.selectedId) ?? undefined;
  const activeResult = useMemo(() => active ? classifyDetailed(active, balancedTraining) : undefined, [active]);
  const balanced = classifyDetailed(clearObservation, balancedTraining);
  const biased = classifyDetailed(ambiguousObservation, biasedTraining);
  const hintCount = progress.hints.ai ?? 0;
  const consult = (id: string) => { setSelectedExample(id); onProgress((current) => ({ ...current, aiMission: { ...current.aiMission, consulted: [...new Set([...current.aiMission.consulted, id])] } })); };
  const reset = () => { game.reset(); setSelectedExample(null); setSelectedObservation(null); setMessage('Mission IA remise au début.'); onProgress((current) => ({ ...current, aiMission: initialAIMission(), hints: without(current.hints, 'ai'), attempts: without(current.attempts, 'ai') })); };
  const finish = () => onProgress((current) => current.aiMission.balancedDone && current.aiMission.biasedDone ? validateFragment(current, 'ai', mission.answer).progress : current);
  return <section className="ai-mission panel panel--wide">
    <div className="component-mission__topline"><button className="back-link" onClick={onBack}>← Retour à la carte</button>{!complete && <button className="button button--quiet" onClick={reset}>↺ Réinitialiser la mission IA</button>}</div>
    <header className="digital-mission-header"><div><p className="eyebrow">Module 6 · Intelligence artificielle</p><h1>Apprendre à la machine à observer le ciel</h1></div><p>Phase <b>{Math.min(phase, 3)}/3</b><br />{phase === 1 ? 'Découvrir' : phase === 2 ? 'Classer' : 'Questionner'}</p></header>
    <p className="ai-lead">La machine d’Antoine d’Abbadie distingue les signaux astronomiques des parasites en comparant chaque observation à des exemples déjà classés. C’est un programme : il ne comprend pas le ciel comme un humain.</p>
    <div className="ai-phase-tabs" aria-label="Progression de la mission"><span className={phase >= 1 ? 'is-active' : ''}>1 · Exemples</span><span className={phase >= 2 ? 'is-active' : ''}>2 · Classement</span><span className={phase >= 3 ? 'is-active' : ''}>3 · Expérience</span></div>
    {phase === 1 && <><p className="ai-instruction">{copy[level].intro}</p><div className="ai-layout"><SkyPlot training={balancedTraining} onExample={consult} /><div className="ai-side"><h2>Mémoire d’apprentissage</h2><p>Chaque exemple porte déjà sa bonne réponse. Touche les quatre points ou leur nom.</p><div className="ai-example-list">{balancedTraining.map((item) => <button className={state.consulted.includes(item.id) ? 'is-seen' : ''} key={item.id} onClick={() => consult(item.id)}>{item.label === 'signal' ? '★' : '◆'} {item.name} <span>{state.consulted.includes(item.id) ? '✓ vu' : 'voir'}</span></button>)}</div>{chosen && <div className="ai-detail" role="status"><h3>{chosen.name} · {chosen.label}</h3><p>Luminosité {chosen.brightness}/10 · régularité {chosen.regularity}/10.</p><p>Cet exemple étiqueté aide la machine à comparer les futures observations.</p></div>}<p>{state.consulted.length}/4 exemples consultés</p><button className="button button--primary" disabled={state.consulted.length < 4} onClick={() => onProgress((current) => ({ ...current, aiMission: { ...current.aiMission, phase: 2 } }))}>La machine a observé les exemples →</button></div></div></>}
    {phase === 2 && <><p className="ai-instruction">{copy[level].classify}</p><div className="ai-layout"><SkyPlot training={balancedTraining} selected={active} result={activeResult} onExample={consult} /><div className="ai-side"><h2>Observations à classer · {Object.keys(game.placements).length}/4</h2><p>Sélectionne une carte, puis touche SIGNAL ou PARASITE. Tu peux aussi la glisser.</p><div className="ai-card-list">{newObservations.filter((item) => !game.placements[item.id]).map((item) => <DraggableItem key={`${item.id}-${game.error?.itemId === item.id ? game.error.nonce : 0}`} itemId={item.id} selected={game.selectedId === item.id} dragging={game.draggingId === item.id} locked={false} errorNonce={game.error?.itemId === item.id ? game.error.nonce : 0} onSelect={(id) => { setSelectedObservation(id); game.selectItem(id); }} onDragStart={(id) => { setSelectedObservation(id); game.startDragging(id); }} onDragEnd={game.stopDragging} onDrop={(id, target) => game.tryPlace(id, target)}><span className="ai-card"><b>◎ {item.name}</b><span>Luminosité {item.brightness} · régularité {item.regularity}</span></span></DraggableItem>)}</div><div className="ai-zones">{(['signal', 'parasite'] as const).map((target) => <DropZone key={target} targetId={target} label={`Famille ${target}`} selectedItemId={game.selectedId ?? game.draggingId} occupied={false} onPlaceSelected={() => game.placeSelected(target)}><b>{target === 'signal' ? '★ SIGNAL' : '◆ PARASITE'}</b><small>{newObservations.filter((item) => game.placements[item.id] === target).map((item) => item.name).join(' · ') || 'Déposer ici'}</small></DropZone>)}</div></div></div><div className="ai-feedback" role="status" aria-live="polite">{game.feedback.message}</div>{active && <div className="ai-detail"><h3>{active.name} · luminosité {active.brightness}, régularité {active.regularity}</h3>{activeResult && <NeighborVote result={activeResult} level={level} />}</div>}{game.complete && <p className="ai-instruction">O1 et O2 : SIGNAL. O3 et O4 : PARASITE. La machine s’appuie sur la proximité des exemples ; sa réponse reste à vérifier.</p>}</>}
    {phase === 3 && <><p className="ai-instruction">{copy[level].experiment}</p><div className="ai-layout"><SkyPlot training={state.biasedDone ? biasedTraining : balancedTraining} selected={state.biasedDone ? ambiguousObservation : clearObservation} result={state.biasedDone ? biased : balanced} /><div className="ai-side"><h2>Expérience 1 · données équilibrées</h2><p>Écho régulier : luminosité 8, régularité 8. Deux signaux et deux parasites ont été montrés au programme.</p><button className="button button--secondary" disabled={state.balancedDone} onClick={() => onProgress((current) => ({ ...current, aiMission: { ...current.aiMission, balancedDone: true } }))}>Analyser le jeu équilibré</button>{state.balancedDone && <NeighborVote result={balanced} level={level} />}{state.balancedDone && <><h2>Expérience 2 · jeu déséquilibré</h2><p>Ajoute des parasites proches, puis observe la lueur inconnue (8, 7).</p><button className="button button--secondary" disabled={state.biasedDone} onClick={() => onProgress((current) => ({ ...current, aiMission: { ...current.aiMission, biasedDone: true } }))}>Ajouter beaucoup d’exemples parasites</button></>}{state.biasedDone && <><p className="ai-balance">★ 1 signal · ◆ 4 parasites</p><NeighborVote result={biased} level={level} /><p className="ai-warning">La machine n’a pas changé ses règles. Ce sont les exemples disponibles qui ont changé sa décision. Ici, le manque d’exemples variés peut produire une mauvaise réponse : une IA peut se tromper sans être cassée. Il faut questionner et vérifier le résultat.</p><button className="button button--primary" onClick={finish}>Conclure l’enquête et révéler le fragment →</button></>}</div></div></>}
    {phase === 4 && <div className="ai-success"><div className="ai-six" aria-label="Fragment découvert : 6"><span>{newObservations.map((item) => <i key={item.id}>{item.name}</i>)}</span><strong>6</strong></div><div><p className="eyebrow">Fragment 6 enregistré automatiquement · module IA allumé</p><h2>Les observations révèlent le 6</h2><p>O1 et O2 : signal. O3 et O4 : parasite.</p><p>Une intelligence artificielle apprend à partir d’exemples. Elle compare de nouvelles données à ce qu’elle connaît déjà. Si ses exemples sont insuffisants ou déséquilibrés, elle peut produire une mauvaise réponse.</p><p>{copy[level].conclusion}</p><button className="button button--primary" onClick={onBack}>Retourner à la carte →</button></div></div>}
    {phase !== 4 && <div className="component-hints"><button className="button button--hint" disabled={hintCount >= mission.hints[level].length} onClick={() => onProgress((current) => ({ ...current, hints: { ...current.hints, ai: Math.min(mission.hints[level].length, (current.hints.ai ?? 0) + 1) } }))}>Obtenir un indice</button>{hintCount > 0 && <ol>{mission.hints[level].slice(0, hintCount).map((hint, index) => <li key={hint}><b>Indice {index + 1}</b>{hint}</li>)}</ol>}</div>}
    <span className="sr-only" role="status">{message}</span>
  </section>;
}
