// @vitest-environment jsdom
import { cleanup,fireEvent,render,screen,waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach,describe,expect,it,vi } from 'vitest';
import { useState } from 'react';
import { getMission } from '../../data/missions';
import { initialProgress,type Progress } from '../../game/progress';
import { EverywhereMission } from './EverywhereMission';
afterEach(cleanup);const mission=getMission('everywhere')!;
function Harness({initial,level='scientist'}:{initial?:Progress;level?:'explorer'|'scientist'|'expert'}){const [progress,setProgress]=useState(initial??{...initialProgress(),level});return <><EverywhereMission mission={mission} progress={progress} onProgress={setProgress} onBack={()=>undefined}/><output data-testid="saved">{JSON.stringify(progress)}</output></>}
async function place(user:ReturnType<typeof userEvent.setup>,item:RegExp,role:RegExp){await user.click(screen.getByRole('button',{name:item}));await user.click(screen.getByRole('button',{name:role}));}
describe('mission Informatique partout',()=>{
  it('place capteur, programme et action par sélection puis dépôt',async()=>{const user=userEvent.setup();render(<Harness/>);await place(user,/Capteur de luminosité/i,/Capteur, observe/i);await place(user,/Règle programmée/i,/Programme, décide/i);await place(user,/Lampe commandée/i,/Action, agit/i);expect(screen.getByRole('button',{name:/Capteur.*contient Capteur de luminosité/i})).toBeTruthy();});
  it('remplace et retire une carte avant validation',async()=>{const user=userEvent.setup();render(<Harness/>);await place(user,/Thermomètre ancien/i,/Capteur, observe/i);await place(user,/Capteur de luminosité/i,/Capteur.*contient Thermomètre/i);expect(screen.getByRole('button',{name:/Retirer Capteur de luminosité/i})).toBeTruthy();await user.click(screen.getByRole('button',{name:/Retirer Capteur de luminosité/i}));expect(screen.getByRole('button',{name:/Capteur de luminosité/i})).toBeTruthy();});
  it('accepte un glissement tactile',()=>{render(<Harness/>);const item=screen.getByRole('button',{name:/Lampe commandée/i});const target=screen.getByRole('button',{name:/Action, agit/i});Object.defineProperty(document,'elementFromPoint',{configurable:true,value:vi.fn(()=>target)});fireEvent.pointerDown(item,{pointerId:3,pointerType:'touch',clientX:2,clientY:2});fireEvent.pointerMove(item,{pointerId:3,pointerType:'touch',clientX:90,clientY:60});fireEvent.pointerUp(item,{pointerId:3,pointerType:'touch',clientX:90,clientY:60});expect(screen.getByRole('button',{name:/Action.*contient Lampe/i})).toBeTruthy();});
  it('explique une chaîne incomplète puis incorrecte',async()=>{const user=userEvent.setup();render(<Harness/>);await user.click(screen.getByRole('button',{name:/Tester le système/i}));await waitFor(()=>expect(screen.getByText(/Il manque un élément/i)).toBeTruthy());await place(user,/Thermomètre ancien/i,/Capteur, observe/i);await place(user,/Règle programmée/i,/Programme, décide/i);await place(user,/Lampe commandée/i,/Action, agit/i);await user.click(screen.getByRole('button',{name:/Tester le système/i}));await waitFor(()=>expect(screen.getByText(/température, pas la lumière/i)).toBeTruthy());});
  it('réussit, révèle 9, persiste et ne montre aucun champ',async()=>{const user=userEvent.setup();render(<Harness/>);await place(user,/Capteur de luminosité/i,/Capteur, observe/i);await place(user,/Règle programmée/i,/Programme, décide/i);await place(user,/Lampe commandée/i,/Action, agit/i);expect(screen.getByTestId('saved').textContent).toContain('"light-sensor":"sensor"');await user.click(screen.getByRole('button',{name:/Tester le système/i}));await waitFor(()=>expect(screen.getByText(/Fragment 5 enregistré automatiquement/i)).toBeTruthy());expect(screen.getByTestId('saved').textContent).toContain('"everywhere":"9"');expect(screen.queryByRole('textbox')).toBeNull();});
  it('restaure puis remet localement la chaîne à zéro',async()=>{const user=userEvent.setup();render(<Harness initial={{...initialProgress(),level:'expert',digitalPlacements:{everywhere:{'light-sensor':'sensor'}}}}/>);expect(screen.getByRole('button',{name:/Retirer Capteur de luminosité/i})).toBeTruthy();await user.click(screen.getByRole('button',{name:/Réinitialiser le laboratoire/i}));expect(screen.getByTestId('saved').textContent).toContain('"everywhere":{}');});
  it('limite Explorateur et enrichit Expert',()=>{const explorer=render(<Harness level="explorer"/>);expect(explorer.container.querySelectorAll('[data-item-id]')).toHaveLength(6);expect(screen.queryByRole('button',{name:/Bouton mécanique/i})).toBeNull();cleanup();render(<Harness level="expert"/>);expect(screen.getByRole('button',{name:/Règle de température/i})).toBeTruthy();expect(screen.getByRole('button',{name:/Sonnette commandée/i})).toBeTruthy();});
});
